const Map<String, String> enUS = {
  "language": "Language",
  "enter_your_phone": "Enter your phone number to Login",
  "send": "Send",
  "phone_number": "Phone number",
  "require_phone_number": "Phone number is required.",
  "syntax_phone_number": "Enter a correct phone number.",
  "phone_number_verification": "Phone number verification",
  "enter_code_we_send": "Enter the code we sent to",
  "not_receive_code": "Didn't receive the code?",
  "resend": "RESEND",
  "send_otp": "OTP code has been sent to",
  "invalid_code": "Invalid code",
  "error_code": "Please enter a valid code.",
  "something_wrong": "Something went wrong.",
  "profile": "Profile",
  "edit": "Edit",
  "history": "History",
  "about": "About us",
  "logout": "Logout",
  "starting": "Starting",
  "earn": "Earn",
  "distance": "Distance",
  "start": "Start",
  "cancel": "Cancel",
  "arrived": "Arrived",
  "success": "Success",
  "failed": "Failed",
  "delivery_complete": "Delivery have been completed.",
  "delivery_failed": "Unable to completed the task.",
  "declined": "Declined",
  "accept": "Accept",
  "new": "New",
  "task_new": "New Task just come in. Let check it.",
  "task_accepted": "Task have been accepted.",
  "task_failed": "Unable to accept this task.",
  "version": "Version",
  "call_now": "Call Now",
  "update_complete": "Profile have been updated successfully.",
  "general_information": "General Information",
  "full_name": "Full Name",
  "male": "Male",
  "female": "Female",
  "number_plate": "Number Plate",
  "date_of_birth": "Date of birth",
  "restaurant": "Restaurant",
  "customer": "Customer",
  "reject": "Reject",
  "remark": "Remark",
  "items": "Items",
  "total": "Total",
  "delivery": "Delivery",
  "description": "Description",
  "size": "Size",
  "type": "Type",
  "discount_total": "Discount total",
  "sub_total": "Sub total",
  "quantity": "Quantity",
  "unit_price": "Unit price",
  "choose_reason": "Choose Reason",
  "waiting_merchant": "Item Order is Preparing. Please confirm with Merchant.",
  "yes": "Yes",
  "no": "No",
  "broken_motorcycle": "Broken motorcycle",
  "traffic_accident": "Traffic accident",
  "other": "Other reason",
  "enter_reason": "Please enter your reasons",
  "write_here": "Write here please",
  "submit": "Submit",
  "task_cancel": "Task have been canceled.",
  "cancel_failed": "Unable to cancel this task.",
  "choose_from_qallery": "Choose from Gallery",
  "take_picture": "Take picture",
  "ask_decline": "Do you want to decline the order?",
  "decline_complete": "Task have been declined.",
  "decline_failed": "Unable to declined the task.",
  "email": "Email address",
  "gender": "Gender",
  "nationality": "Nationality",
  "marital_status": "Marital Status",
  "address": "Address",
  "website": "Website",
  "user_name": "Username",
  "personal_information": "Personal Information",
};
